#!/bin/bash

recordIn ()
{
    local STORE_INvar="${1}" ; shift
	eval "$( printf '%s="%q"' "${STORE_INvar}" "$@" )"
}

as ()
{
    local STORE_INvar="${1}" ; shift
	eval ${STORE_INvar}=\""$( "$@" 2>&1 )"\"
}

as ()
{
    local STORE_INvar="${1}" ; shift
	#eval ${STORE_INvar}=\""$( "$@" 2>&1 )"\"
	#eval "${STORE_INvar}='$( "$@" 2>&1 )'"
	#eval "${STORE_INvar}"=\""$( eval \""$@"\" 2>&1 )"\"
	eval "${STORE_INvar}"=\"'$( '$@' 2>&1 ; printf %s x ; )'\"
	echo -n "${!STORE_INvar}" | wc -c
	${STORE_INvar}='${!STORE_INvar%x}'
	echo -n "${!STORE_INvar}" | wc -c
	# eval "$var='$val'"
	echoDebug "Just Executed: '$@'"
}

as ()
{
    local STORE_INvar="${1}" ; shift
	# IFS='' read -d '' "${STORE_INvar}" <<<"$( $@ ; echo -n x )"
	IFS='' read -d '' "${STORE_INvar}" <<<"$( $@ ; echo -n x )"
    eval \"'${STORE_INvar}=${!STORE_INvar%x}'\"
}

as ()
{
    local STORE_INvar="${1}" ; shift
	# IFS='' read -d '' "${STORE_INvar}" <<<"$( $@ ; echo -n x )"
	IFS='' read -d '' "${STORE_INvar}" <<<"$( $@ ; echo -n x )"
    eval \"'${STORE_INvar}=${!STORE_INvar%x}'\"
}

as ()
{
    local STORE_INvar="${1}" ; shift
	local BUFFER="$( "$@" ; printf %s x ; )"
	# IFS='' read -d '' "${STORE_INvar}" <<<"$( $@ ; echo -n x )"
	#"${STORE_INvar}" <<<"$( $@ ; echo -n x )"
    #eval \"'${STORE_INvar}=${!STORE_INvar%x}'\"
    printf -v "${STORE_INvar}" %s "${BUFFER%x}"
}

as ()
{
    local STORE_INvar="${1}" ; shift
	local BUFFER="$( "$@" ; printf %s x ; )"
    printf -v "${STORE_INvar}" %s "${BUFFER%x}"
}

into ()
{
    local STORE_INvar="${1}" ; shift
    # local BUFFERstr=$( cat ; echo -n x )
    # BUFFERstr=${BUFFERstr%x}
#	myVar=$(cat; echo -n x)
#	myVar=${myVar%x}
#	printf %s "$myVar"

# var=$(echo -n $'\n'; echo -n x); var="${var%x}"; echo -n "$var" # $var == "\n"
	eval ${STORE_INvar}=\""$( "$@" 2>&1 )"\"
#	eval "${STORE_INvar}='$( "$@" 2>&1 )'"
	#eval "${STORE_INvar}"=\""$( eval \""$@"\" 2>&1 )"\"
#	eval "${STORE_INvar}"=\"'$( 'cat -' 2>&1 )'\"
	#eval "${STORE_INvar}"=\"'$( cat - 2>&1 )'\"
	#eval "${STORE_INvar}"='\$\( cat \)'
#	eval "${STORE_INvar}"=\"'\$\( cat \)'\"
	# eval "$var='$val'"
	echoDebug "Just Executed: '${STORE_INvar}=\$( cat - )'"
}

asEval ()
{
    local STORE_INvar="${1}" ; shift
	eval "${STORE_INvar}"=\"'\$( '$@' 2>&1 ; printf %s x ; )'\"
	printf %s -v "${STORE_INvar}" "${!STORE_INvar%x}"
}

asDirect ()
{
    local VARIABLEptr="${1}" ; shift
	printf -v "${VARIABLEptr}" %s "$( "$@" ; )"
}

as ()
{
    local VARIABLEptr="${1}" ; shift
	printf -v "${VARIABLEptr}" %s "$( echo \""$@"\" ; printf %s x ; )"
    printf -v "${VARIABLEptr}" %s "${!VARIABLEptr%x}"
}

asif ()
{
    local VARIABLEptr="${1}" ; shift
	printf -v "${VARIABLEptr}" %s "$( cat - ; printf %s x ; )"
    printf -v "${VARIABLEptr}" %s "${!VARIABLEptr%x}"
}

storeIn ()
{
    local STORE_INvar="${1}" ; shift
	eval ${STORE_INvar}="$( "$@" 2>&1 )"
}
